name: nader_driver
description: "A new Flutter project."

publish_to: 'none' # Remove this 
version: 2.0.0+8

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  http: ^1.4.0
  flutter_otp_text_field: ^1.5.1+1
  country_code_picker: ^3.3.0
  image_picker: ^1.1.2
  dropdown_button2: ^2.3.9
  dotted_border: ^2.1.0
  pinput: ^5.0.1
  flutter_spinkit: ^5.2.1
  google_maps_flutter: ^2.12.2
  geolocator: ^14.0.0
  fluttertoast: ^8.2.12
  buttons_tabbar: ^1.3.15
  jwt_decoder: ^2.0.1
  geocoding: ^3.0.0
  google_places_flutter: ^2.1.0
  flutter_google_maps_webservices: ^1.1.1
  permission_handler: ^12.0.1
  location: ^8.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5
  flutter_svg: ^2.1.0
  flutter_polyline_points: ^2.1.0
  intro_slider: ^4.2.1
  intl_phone_field: ^3.2.0
  logger: ^2.6.1
  web_socket_client: ^0.2.1
  file_picker: ^10.2.1
  popover: ^0.3.1
  shimmer: ^3.0.0
  dio: ^5.8.0+1
  url_launcher: ^6.3.1
  intl: ^0.20.2
  web_socket_channel: ^3.0.3
  http_parser: ^4.1.2

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5

  # Auth & UI
  google_sign_in: ^6.0.1
  flutter_signin_button: ^2.1.1
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/applogo.png"
  remove_alpha_ios: true
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

